<a href="https://colab.research.google.com/github/hyunjiHong/std_NLP/blob/master/tutorial_package.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. Pandas**

---


파이썬 데이터 처리를 위한 라이브러리 

###데이터 구조

####1) Series
1차원 배열, index, values로 구성

In [2]:
import pandas as pd
data = pd.Series([1,2,3], index=["호박","고구마","단호박"])
print(data)
print(data.values)
print(data.index)

호박     1
고구마    2
단호박    3
dtype: int64
[1 2 3]
Index(['호박', '고구마', '단호박'], dtype='object')


####2) DataFrame
2차원 리스트, 열(columns), 인덱스(index), 값(values)으로 구성

In [5]:
values = [[1,2,3],[4,5,6],[7,8,9]]
index = ['호박', '고구마', '단호박']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values,index=index,columns=columns)
print(df)
print(df.index)
print(df.columns)
print(df.values)

     A  B  C
호박   1  2  3
고구마  4  5  6
단호박  7  8  9
Index(['호박', '고구마', '단호박'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]


데이터 프레임은 리스트, 시리즈, 딕셔너리, ndarrays로 생성할 수 있음 

In [6]:
#dictionary로 생성
data = { '학번' : ['1000', '1001', '1002', '1003', '1004', '1005'],
'이름' : [ 'Steve', 'James', 'Doyeon', 'Jane', 'Pilwoong', 'Tony'],
         '점수': [90.72, 78.09, 98.43, 64.19, 81.30, 99.14]}

df = pd.DataFrame(data)
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


###2-2) 데이터 프레임 응용

####유용한 명령어
* df.head(n)
* df.tail(n)
* df['columns name']

In [8]:
print(df.head(2))
print(df.tail(2))
print(df['학번'])

     학번     이름     점수
0  1000  Steve  90.72
1  1001  James  78.09
     학번        이름     점수
4  1004  Pilwoong  81.30
5  1005      Tony  99.14
0    1000
1    1001
2    1002
3    1003
4    1004
5    1005
Name: 학번, dtype: object


#**2. Numpy**

---


* 수치 데이터를 다루는 파이썬 패키지
* 다차원 행렬 자료구조인 ndarray를 통해 벡터 및 행렬을 사용하는 **선형대수** 계산에서 사용


###0) 주요 모듈
1. np.array() # 리스트, 튜플, 배열로 부터 ndarray를 생성
2. np.asarray() # 기존의 array로 부터 ndarray를 생성
3. np.arange() # range와 비슷
4. np.linspace(start, end, num) # [start, end] 균일한 간격으로 num개 생성
5. np.logspace(start, end, num) # [start, end] log scale 간격으로 num개 생성

###1) np.array()
리스트, 튜플, 배열로 부터 ndarray를 생성

In [15]:
import numpy as np

a = np.array([[10, 20, 30], [ 60, 70, 80]]) #리스트를 가지고 1차원 배열 생성
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[10 20 30]
 [60 70 80]]


In [16]:
#행렬의 차원 및 크기를 출력
print(a.ndim)
print(a.shape)

2
(2, 3)


###2) np.arange()
지정해준 범위에 대해서 배열을 생성


*  numpy.arange(start, stop, step, dtype)
* a = np.arange(n) # 0, ..., n-1까지 범위의 지정.
* a = np.arange(i, j, k) # i부터 j-1까지 k씩 증가하는 배열.



In [18]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

###3) reshape()

In [21]:
a = np.array(np.arange(30)).reshape((5,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

###4) numpy slicing

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b=a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


###5) numpy 연산
+, -, *, /의 연산자를 사용할 수 있으며, 또는 add(), substract(), multiply(), divide() 함수 사용가능

  *asterisk를 통해 수행한 것은 요소별 곱. Numpy에서 벡터와 행렬의 곱 또는 행렬곱을 위해서는 dot()을 사용*



In [23]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]


#**3. Matplotlib**

---
데이터를 차트나 플롯으로 시각화한 패키지
* 데이터 이해를 위한 시각화
* 데이터 분석 후 결과를 시각화